sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t gmateosaws/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gmateosaws/react-test npm test

after_success: 
  - docker build -t gmateosaws/fibonacci-client ./client
  - docker build -t gmateosaws/fibonacci-nginx ./nginx
  - docker build -t gmateosaws/fibonacci-server ./server
  - docker build -t gmateosaws/fibonacci-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docher hub
  - docker push gmateosaws/fibonacci-client
  - docker push gmateosaws/fibonacci-nginx
  - docker push gmateosaws/fibonacci-server
  - docker push gmateosaws/fibonacci-worker

deploy:
  provider: elasticbeanstalk
  edge: true
  region: "eu-west-3"
  app: "fibonacci"
  env: "Fibonacci-env"
  bucket-name: "elasticbeanstalk-eu-west-3-478344394470"
  bucket-path: "fibonacci"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: "$AWS_SECRET_ACCESS_KEY"
