sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t gmateosaws/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true gmateosaws/react-test npm test

after_success: 
  - docker build -t gmateosaws/fibonacci-client ./client
  - docker build -t gmateosaws/fibonacci-nginx ./nginx
  - docker build -t gmateosaws/fibonacci-server ./server
  - docker build -t gmateosaws/fibonacci-worker ./worker